name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: go build -o bin/sentinel-ai ./cmd/sentinel-ai

    - name: Test
      run: go test ./...

    - name: Lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest

    - name: Test CLI
      run: |
        ./bin/sentinel-ai --help
        ./bin/sentinel-ai scan --help
        ./bin/sentinel-ai apply --help
        ./bin/sentinel-ai pr --help

    - name: Test with example
      run: |
        mkdir -p out
        ./bin/sentinel-ai scan --repo ./example --security --dead-code --sarif ./out/example.sarif --plan ./out/example-plan.json
        cat out/example.sarif
        cat out/example-plan.json
